#include "DataManager.h"

int id = 7;
int day = 0;
bool broken = false;

void setup() {
  Serial.begin(9600);
}

void loop() {
    Data data;
    Data* data_ptr = &data;
    data_ptr->id = id;

    // Generate random number
    float random_number = random(0, 10000) / 10000.0; // Random number between 0 and 1;
    if (random_number < calculate_probability(day) || broken) {
        grab_random_bad(data_ptr);
        Serial.println("Bad data generated");
        broken = true;
    } else {
        grab_random_good(data_ptr);
        Serial.println("Good data generated");
    }

    // Send data struct in JSON format (timestamp is generated by receiver)
    String json = "{";
    json += "\"id\":" + String(data_ptr->id) + ",";
    json += "\"tp2\":" + String(data_ptr->tp2) + ",";
    json += "\"tp3\":" + String(data_ptr->tp3) + ",";
    json += "\"h1\":" + String(data_ptr->h1) + ",";
    json += "\"dv_pressure\":" + String(data_ptr->dv_pressure) + ",";
    json += "\"resevoirs\":" + String(data_ptr->resevoirs) + ",";
    json += "\"oil_temperature\":" + String(data_ptr->oil_temperature) + ",";
    json += "\"motor_current\":" + String(data_ptr->motor_current) + ",";
    json += "\"COMP\":" + String(data_ptr->COMP) + ",";
    json += "\"dv_electric\":" + String(data_ptr->dv_electric) + ",";
    json += "\"towers\":" + String(data_ptr->towers) + ",";
    json += "\"mpg\":" + String(data_ptr->mpg) + ",";
    json += "\"lps\":" + String(data_ptr->lps) + ",";
    json += "\"pressure_switch\":" + String(data_ptr->pressure_switch) + ",";
    json += "\"oil_level\":" + String(data_ptr->oil_level) + ",";
    json += "\"caudal_impulses\":" + String(data_ptr->caudal_impulses);
    json += "}";

    Serial.println(json);

    day++;
    delay(10000);
}
