#include "DataManager.h"

int component_id = 1; // ID of the "component"
int train_id = 1;
int iteration = 0;
bool broken = false; // If component is broken, it won't be magically fixed.

void setup() {
  Serial.begin(9600);
}

void loop() {
    Data data;
    Data* data_ptr = &data;
    data_ptr->component_id = component_id;
    data_ptr->train_id = train_id;

    randomSeed(analogRead(0));

    // Generate random number
    float random_number = random(0, 10000) / 10000.0; 
    if (random_number < calculate_probability(iteration) || broken) {
        grab_random_bad(data_ptr);
        Serial.println("Bad data generated");
        broken = true;
    } else {
        grab_random_good(data_ptr);
        Serial.println("Good data generated");
    }

    // Send data struct in JSON format (timestamp is generated by receiver)
    String json = "{";
    json += "\"component_id\":" + String(data_ptr->component_id) + ",";
    json += "\"train_id\":" + String(data_ptr->train_id) + ",";
    json += "\"tp2\":" + String(data_ptr->tp2) + ",";
    json += "\"tp3\":" + String(data_ptr->tp3) + ",";
    json += "\"h1\":" + String(data_ptr->h1) + ",";
    json += "\"dv_pressure\":" + String(data_ptr->dv_pressure) + ",";
    json += "\"resevoirs\":" + String(data_ptr->resevoirs) + ",";
    json += "\"oil_temperature\":" + String(data_ptr->oil_temperature) + ",";
    json += "\"motor_current\":" + String(data_ptr->motor_current) + ",";
    json += "\"COMP\":" + String(data_ptr->COMP) + ",";
    json += "\"dv_electric\":" + String(data_ptr->dv_electric) + ",";
    json += "\"towers\":" + String(data_ptr->towers) + ",";
    json += "\"mpg\":" + String(data_ptr->mpg) + ",";
    json += "\"lps\":" + String(data_ptr->lps) + ",";
    json += "\"pressure_switch\":" + String(data_ptr->pressure_switch) + ",";
    json += "\"oil_level\":" + String(data_ptr->oil_level) + ",";
    json += "\"caudal_impulses\":" + String(data_ptr->caudal_impulses);
    json += "}";

    Serial.println(json);

    iteration++;
    delay(300000); // 5 minutes delay
}
